

import { AllFilters } from "@/components/AllFilters";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "LEVEL UP - Todos los productos",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
        <main className={``}>
          <AllFilters/>
        {children}
        </main>
        
  );
}
