

import { AllFilters } from "@/components/AllFilters";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "LEVEL UP - Todos los productos",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <main className="mt-8 xl:max-w-[1200px] mx-auto relative overflow-x-hidden">
          
        {children}
        </main>
        
  );
}
